import {isHiddenToken,visibleListings} from './lib/listings.mjs';
import {initRewards} from './rewards.js';
import {BY_ID,assetFromKey,referenceKey,ownTokens} from './lib/assets.mjs';
import {initCatalogue,refreshCatalogue,updateReferenceDetail,assetQuote,displayQuote,requestQuotes,requirePricedReference} from './catalog.js';
import {parseAmount,minOutput,curveQuote,feedStatus,escapeHTML as esc,validTokenFields} from './lib/market.mjs';
const E=window.ethers,C={...window.ANYPAIR_CONFIG},$=s=>document.querySelector(s),fmt=E.formatEther;
const LOCAL=['127.0.0.1','localhost'].includes(location.hostname)&&new URLSearchParams(location.search).get('qa')==='1';
const PAIR='tuple(address token,bytes32 feedId,string assetKey,uint256 realBnb,uint256 tokenReserve,uint256 basePriceAtLaunch,address creator,uint64 createdAt,bool graduated)';
const PAD_ABI=[`function getPairs(uint256,uint256) view returns (${PAIR}[])`,`function getPair(address) view returns (${PAIR})`,
 'function pairsCount() view returns(uint256)','function oracle() view returns(address)','function router() view returns(address)',
 'function currentPrice(address) view returns(uint256)','function graduationProgress(address) view returns(uint256)',
 'function quoteBuy(address,uint256) view returns(uint256)','function quoteSell(address,uint256) view returns(uint256)',
 'function creationFee() view returns(uint256)','function graduationThreshold() view returns(uint256)','function virtualBnb() view returns(uint256)','function FEE_BPS() view returns(uint256)',
 'function buy(address,uint256) payable returns(uint256)','function sell(address,uint256,uint256) returns(uint256)',
 'function createPair(string,string,string,bytes32,uint256) payable returns(address)',
 'event PairCreated(address indexed token,address indexed creator,string name,string symbol,string assetKey,bytes32 feedId,uint256 basePriceAtLaunch)'];
const ORACLE_ABI=['function feedCount() view returns(uint256)','function feedIds(uint256) view returns(bytes32)','function maxStale() view returns(uint256)','function feeds(bytes32) view returns(uint256 price,uint64 updatedAt,uint8 tier,bool exists,string description)'];
const ERC20_ABI=['function name() view returns(string)','function symbol() view returns(string)','function balanceOf(address) view returns(uint256)','function totalSupply() view returns(uint256)','function approve(address,uint256) returns(bool)','function allowance(address,address) view returns(uint256)'];
const POOL_ABI=['function getReserves() view returns(uint112,uint112,uint32)','function token0() view returns(address)'];
const TIER=['REAL','INDEX','LARP'],TIERCLS=['b-real','b-index','b-larp'],DEAD='0x000000000000000000000000000000000000dEaD';
let rpc,pad,oracle,router,factory,wrapped,settings,feeds=[],secs=[],selected,side='buy',hist={},baseline={},metadata=new Map();
let injected,browserProvider,signer,me='',padWrite,busy=false,connecting=false,polling=false,quote,quoteVersion=0,launchReview,pendingHash='';
let rewards;let timer,clockTimer,marketScope='mine';const wallets=[];
const short=a=>a.slice(0,6)+'…'+a.slice(-4),decimal=n=>fmt(n),human=n=>Number(fmt(n)).toLocaleString('en-US',{maximumSignificantDigits:8});
const nBNB=n=>(Number(n)/1e9).toLocaleString('en-US',{maximumSignificantDigits:7});
const usd=n=>Number(n).toLocaleString('en-US',{style:'currency',currency:'USD',maximumSignificantDigits:7});
function status(message,hash){const box=$('#st-msg');box.replaceChildren(document.createTextNode(message));if(hash&&/^0x[\da-f]{64}$/i.test(hash)){const a=document.createElement('a');a.textContent=' VIEW TX ↗';a.href=C.EXPLORER+'/tx/'+hash;a.target='_blank';a.rel='noopener noreferrer';box.append(a)}}
function errorText(e){if(e.code==='ACTION_REJECTED'||e.code===4001)return 'Request declined in wallet.';if(e.code===-32002)return 'A wallet request is already open. Complete it in your wallet.';if(e.code==='INSUFFICIENT_FUNDS')return 'Insufficient BNB for the amount and network fee.';return String(e.reason||e.shortMessage||e.message||e).slice(0,350)}
function invalidateQuote(){quote=null;quoteVersion++;$('#i-min').textContent='—';updateExecLabel()}
function invalidateLaunch(){launchReview=null;$('#launch-review').hidden=true;$('#f-confirm').hidden=true;$('#f-status').textContent=''}
function setBusy(value){busy=value;for(const id of ['#netbtn','#f-deploy','#f-confirm','#f-name','#f-ticker','#f-feed','#f-buy','#amt','#slippage','#tab-buy','#tab-sell','#f-rewards','#f-reward-budget','#f-reward-days'])$(id).disabled=value;$('#quick').querySelectorAll('button').forEach(b=>b.disabled=value);updateExecLabel();if(!value)rewards?.ready()}
function remember(tx,kind,token){const owner=E.getAddress(tx.from);pendingHash=tx.hash;try{localStorage.setItem('anypair:pending:'+C.LAUNCHPAD.toLowerCase()+':'+owner.toLowerCase(),JSON.stringify({hash:tx.hash,nonce:tx.nonce,kind,token,from:owner,at:Date.now()}))}catch{}status('Transaction sent. Waiting for confirmation.',tx.hash)}
function forget(owner=me){pendingHash='';try{localStorage.removeItem('anypair:pending:'+C.LAUNCHPAD.toLowerCase()+':'+owner.toLowerCase())}catch{}}
async function waitMined(tx,kind,token){remember(tx,kind,token);const owner=E.getAddress(tx.from);let receipt;try{receipt=await tx.wait(1,120000)}catch(e){if(e.code==='TRANSACTION_REPLACED'){forget(owner);if(e.cancelled)throw Error('Transaction cancelled or replaced in your wallet.');receipt=e.receipt;status('Replacement transaction confirmed.',e.replacement.hash)}else throw e}if(!receipt)throw Error('Confirmation is still pending. Use the transaction link; do not submit again.');forget(owner);if(receipt.status!==1)throw Error('Transaction failed on-chain. Network fees may have been charged.');return receipt}
async function recoverPending(){let record;try{record=JSON.parse(localStorage.getItem('anypair:pending:'+C.LAUNCHPAD.toLowerCase()+':'+me.toLowerCase())||'null')}catch{}if(!record||!/^0x[\da-f]{64}$/i.test(record.hash))return;const receipt=await rpc.getTransactionReceipt(record.hash);if(receipt){forget();status(receipt.status===1?'Previous transaction confirmed.':'Previous transaction failed.',record.hash);return}if(Number.isInteger(record.nonce)&&(await rpc.getTransactionCount(me,'latest'))>record.nonce){forget();status('Previous transaction nonce was used. Check wallet activity before placing another order.',record.hash);return}pendingHash=record.hash;status('Previous transaction is pending. Check your wallet or refresh after confirmation.',record.hash)}

/* Multiple wallets are discovered without assuming which extension owns window.ethereum. */
function addWallet(detail){if(!detail?.provider||wallets.some(w=>w.provider===detail.provider))return;wallets.push(detail);renderWallets()}
window.addEventListener('eip6963:announceProvider',e=>addWallet(e.detail));
function discover(){window.dispatchEvent(new Event('eip6963:requestProvider'));const e=window.ethereum;if(e)for(const provider of e.providers||[e])addWallet({provider,info:{name:provider.isMetaMask?'MetaMask (injected)':provider.isTrust?'Trust Wallet':'Browser wallet'}})}
function renderWallets(){const box=$('#wallet-options');box.replaceChildren();if(!wallets.length){box.textContent='No wallet detected in this browser.';$('#wallet-help').textContent='Open this site in a browser with a wallet extension or in your mobile wallet’s browser.';return}$('#wallet-help').textContent='Choose a wallet above, then confirm the connection in its popup.';for(const wallet of wallets){const b=document.createElement('button');b.disabled=connecting;b.type='button';b.textContent=String(wallet.info?.name||'Browser wallet').slice(0,80);b.onclick=()=>connect(wallet.provider);box.append(b)}}
function openWallet(){if(busy||connecting)return;if(LOCAL){connect(null);return}$('#wallet-status').textContent='';discover();renderWallets();$('#wallet-dialog').showModal()}
function disconnect(){me='';renderTable();signer=padWrite=null;pendingHash='';invalidateQuote();invalidateLaunch();$('#netdot').classList.remove('on');$('#netlbl').textContent='CONNECT WALLET';$('#st-addr').textContent='WALLET: —';$('#bal').textContent='NOT CONNECTED';status('Wallet account or network changed. Connect again.');updateExecLabel();rewards?.changed()}
async function ensureChain(){if(LOCAL)return;const target=Number(C.CHAIN_ID);if(Number(await injected.request({method:'eth_chainId'}))!==target){try{await injected.request({method:'wallet_switchEthereumChain',params:[{chainId:C.CHAIN_HEX}]})}catch(e){if(e.code!==4902)throw e;await injected.request({method:'wallet_addEthereumChain',params:[{chainId:C.CHAIN_HEX,chainName:C.CHAIN_NAME,nativeCurrency:{name:'BNB',symbol:'BNB',decimals:18},rpcUrls:[C.RPC_URL],blockExplorerUrls:[C.EXPLORER]}]});await injected.request({method:'wallet_switchEthereumChain',params:[{chainId:C.CHAIN_HEX}]})}}if(Number(await injected.request({method:'eth_chainId'}))!==target)throw Error('Switch your wallet to BNB Chain before continuing.')}
async function connect(provider){if(connecting||busy)return;connecting=true;renderWallets();$('#wallet-status').textContent='Waiting for your wallet. Open the wallet extension and confirm the connection.';try{injected?.removeListener?.('accountsChanged',disconnect);injected?.removeListener?.('chainChanged',disconnect);injected=provider;status('Open your wallet to connect…');if(!LOCAL)await injected.request({method:'eth_requestAccounts'});await ensureChain();browserProvider=LOCAL?rpc:new E.BrowserProvider(injected,undefined,{cacheTimeout:-1});signer=await browserProvider.getSigner();me=await signer.getAddress();padWrite=new E.Contract(C.LAUNCHPAD,PAD_ABI,signer);if(injected){injected.on?.('accountsChanged',disconnect);injected.on?.('chainChanged',disconnect)}$('#wallet-dialog').close();$('#netdot').classList.add('on');$('#netlbl').textContent=short(me);$('#st-addr').textContent='WALLET: '+short(me);await updateBal().catch(()=>{$('#bal').textContent='BALANCE UNAVAILABLE'});status(LOCAL?'LOCAL FORK WALLET · TEST FUNDS':'Wallet connected · '+short(me));renderTable();await recoverPending();await recalc()}catch(e){disconnect();$('#wallet-status').textContent='Connection not completed: '+errorText(e);status('Connect failed: '+errorText(e))}finally{connecting=false;renderWallets();updateExecLabel();rewards?.changed()}}
async function verifyWallet(){if(!me||!signer)throw Error('Connect your wallet first.');if(!LOCAL){const [chain,accounts]=await Promise.all([injected.request({method:'eth_chainId'}),injected.request({method:'eth_accounts'})]);if(Number(chain)!==C.CHAIN_ID||!accounts[0]||E.getAddress(accounts[0])!==me){disconnect();throw Error('Wallet changed. Connect again before signing.')}}}
async function updateBal(){if(!me)return;const [bnb,tokens]=await Promise.all([rpc.getBalance(me),selected?new E.Contract(selected,ERC20_ABI,rpc).balanceOf(me):0n]);$('#bal').textContent=human(bnb)+' BNB · '+human(tokens)+' '+(secs.find(s=>s.token===selected)?.sym||'TOKENS')}

/* Read only chain state: feeds, curve configuration and actual DEX reserves. */
async function loadSettings(){const [fee,threshold,virtual,feeBps,stale]=await Promise.all([pad.creationFee(),pad.graduationThreshold(),pad.virtualBnb(),pad.FEE_BPS(),oracle.maxStale()]);settings={fee,threshold,virtual,feeBps,stale:Number(stale)};$('#about-config').textContent='Current graduation threshold: '+decimal(threshold)+' BNB held on the curve. Creation fee: '+decimal(fee)+' BNB. Curve trades carry a '+Number(feeBps)/100+'% fee. Network fees are additional. Trading after graduation takes place on PancakeSwap.'}
async function loadFeeds(){const n=Number(await oracle.feedCount()),list=[];for(let offset=0;offset<n;offset+=20){list.push(...await Promise.all(Array.from({length:Math.min(20,n-offset)},async(_,i)=>{const id=await oracle.feedIds(offset+i),f=await oracle.feeds(id);return{id,tier:Number(f.tier),desc:f.description,price:f.price,updatedAt:Number(f.updatedAt)}})))}feeds=list;feedDetail();refreshCatalogue()}
function oracleQuote(asset){const f=feeds.find(f=>f.id===E.id(asset.feedKey||''));return f?{value:Number(fmt(f.price))/(asset.divisor||1),currency:'USD',tier:f.tier,asOf:new Date(f.updatedAt*1000).toISOString(),status:feedStatus(f.updatedAt,settings?.stale||3600)+' · '+TIER[f.tier]+' on-chain reference'}:undefined}
function feedDetail(){updateReferenceDetail($('#f-feed').value)}
function launchChoice(){const id=$('#f-feed').value,a=BY_ID.get(id);if(!a)throw Error('Choose an asset with an available price.');const asset=referenceKey(id),feedId=a.provider==='oracle'&&feeds.some(f=>f.id===E.id(a.feedKey))?E.id(a.feedKey):E.ZeroHash;return {asset,feedId,label:a.name,id}}
function openLaunch(id){if(busy)return;if(typeof id==='string'){$('#f-feed').value=id;invalidateLaunch();feedDetail()}$('#ovl').classList.add('on');$('#f-name').focus()}
async function readSecurity(p){let meta=metadata.get(p.token);if(!meta){const token=new E.Contract(p.token,ERC20_ABI,rpc);const [sym,name]=await Promise.all([token.symbol(),token.name()]);meta={sym,name};metadata.set(p.token,meta)}const feed=feeds.find(f=>f.id===p.feedId);let price=0n,pool=E.ZeroAddress,poolBnb=0n,supply=10n**27n;if(!p.graduated)price=await pad.currentPrice(p.token);else{pool=await factory.getPair(p.token,wrapped);if(pool!==E.ZeroAddress){const pair=new E.Contract(pool,POOL_ABI,rpc);const [r,t0,burned]=await Promise.all([pair.getReserves(),pair.token0(),new E.Contract(p.token,ERC20_ABI,rpc).balanceOf(DEAD)]);const first=t0.toLowerCase()===p.token.toLowerCase(),tokenReserve=r[first?0:1];poolBnb=r[first?1:0];price=tokenReserve?poolBnb*10n**18n/tokenReserve:0n;supply-=burned}}
 const grad=p.graduated?10000:Math.min(10000,Number(p.realBnb*10000n/settings.threshold));return{...meta,token:p.token,asset:assetFromKey(p.assetKey)?.name||p.assetKey,reference:assetFromKey(p.assetKey),feedId:p.feedId,creator:p.creator,realBnb:p.realBnb,tokenReserve:p.tokenReserve,graduated:p.graduated,price,grad,feed,pool,poolBnb,supply}}
async function loadSecurities(){const count=Number(await pad.pairsCount()),raw=[];const start=Math.max(0,count-200);for(let offset=start;offset<count;offset+=30)raw.push(...await pad.getPairs(offset,Math.min(30,count-offset)));const listed=visibleListings(raw),out=[];for(let i=0;i<listed.length;i+=6)out.push(...await Promise.all(listed.slice(i,i+6).map(readSecurity)));secs=out;if(isHiddenToken(selected))selected=undefined;const now=Date.now();for(const s of secs){if(baseline[s.token]===undefined)baseline[s.token]=Number(s.price);const h=hist[s.token]||[];h.push({price:Number(s.price),at:now});if(h.length>120)h.shift();hist[s.token]=h}$('#pcount').textContent=secs.length+' TOKENS';if(!selected){const initial=marketScope==='all'?secs[0]:ownTokens(secs,me)[0];if(initial)selected=initial.token;}renderTable();renderTicker();if(selected)renderSelected();updateExecLabel()}
function renderTable(){const body=$('#sectbody'),visible=marketScope==='mine'?ownTokens(secs,me):secs;$('#pcount').textContent=visible.length+' TOKENS'+(secs.length>=200?' · LATEST 200 SCANNED':'');if(!visible.length){body.innerHTML='<tr><td colspan="6" class="l dim empty-row">'+(marketScope==='mine'&&!me?'Connect your wallet to see the tokens you created.':marketScope==='mine'?'Your launches will appear here. Create your first token above.':'No listed tokens yet. Create a token above.')+'</td></tr>';return}body.innerHTML=visible.map(s=>{const chg=baseline[s.token]?(Number(s.price)/baseline[s.token]-1)*100:0;const state=s.feed?feedStatus(s.feed.updatedAt,settings.stale):'NO REF';return `<tr tabindex="0" role="button" aria-label="Select ${esc(s.sym)}" data-t="${s.token}" class="${selected===s.token?'sel':''}"><td class="l tk">${esc(s.sym)}</td><td class="wht">${s.price?nBNB(s.price):'—'}</td><td class="${chg<0?'red':'grn'}">${chg>=0?'+':''}${chg.toFixed(1)}</td><td>${human(s.graduated?s.poolBnb:s.realBnb)}</td><td>${(s.grad/100).toFixed(0)}</td><td class="l">${esc(s.asset)} <span class="badge ${s.graduated?'b-grad':state==='STALE'?'b-stale':TIERCLS[s.feed?.tier??2]}">${s.graduated?'DEX POOL':state==='STALE'?'STALE':s.feed?TIER[s.feed.tier]:s.reference?.provider==='meme'?'MEME':s.reference?'REFERENCE':'NO REF'}</span></td></tr>`}).join('');body.querySelectorAll('[data-t]').forEach(row=>{row.onclick=()=>select(row.dataset.t);row.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(row.dataset.t)}}})}
function renderTicker(){const items=secs.map(s=>`<span class="it"><b>${esc(s.sym)}</b> ${s.price?nBNB(s.price)+' nBNB':'NO LIQUIDITY'} · ${s.graduated?'PANCAKESWAP':'CURVE'}</span>`).join('');$('#ticker').innerHTML=items+items}
function addLink(label,url){const a=document.createElement('a');a.textContent=label+' ↗';a.href=url;a.target='_blank';a.rel='noopener noreferrer';$('#market-links').append(a)}
function renderSelected(){const s=secs.find(x=>x.token===selected);if(!s)return;$('#des-tk').textContent=s.sym;$('#des-name').textContent=s.name;$('#des-self').textContent='$'+s.sym;$('#des-asset').textContent=s.asset||'No asset reference';$('#des-tier').textContent=s.graduated?'PANCAKESWAP V2':s.feed?TIER[s.feed.tier]+' REFERENCE':s.reference?.provider==='meme'?'MEME REFERENCE':s.reference?'EXTERNAL REFERENCE':'NO REFERENCE';$('#des-last').textContent=s.price?nBNB(s.price)+' nBNB':'No pool liquidity';$('#des-mcap').textContent=s.price?human(s.price*s.supply/10n**18n)+' BNB':'—';$('#des-rsv').textContent=decimal(s.graduated?s.poolBnb:s.realBnb)+' BNB'+(s.graduated?' · DEX pool':' · curve');$('#des-oracle').textContent=s.feed?usd(Number(fmt(s.feed.price)))+' ['+TIER[s.feed.tier]+']':'No reference';$('#des-updated').textContent=s.feed?feedStatus(s.feed.updatedAt,settings.stale)+' · '+new Date(s.feed.updatedAt*1000).toLocaleString('en-GB'):'—';if(s.reference){const q=s.reference.provider==='oracle'?oracleQuote(s.reference):assetQuote(s.reference.id);$('#des-oracle').textContent=q?.value!==undefined?displayQuote(q)+' / '+s.reference.unit:s.reference.provider==='meme'?'Fictional meme · no market quote':'No verified quote';$('#des-updated').textContent=q?.asOf?q.status+' · '+q.asOf:'—'}$('#des-addr').replaceChildren();const a=document.createElement('a');a.href=C.EXPLORER+'/token/'+s.token;a.textContent=s.token;a.className='dim';a.target='_blank';a.rel='noopener noreferrer';$('#des-addr').append(a);$('#gradfill').style.width=s.grad/100+'%';$('#gradtxt').textContent=s.graduated?'DEX POOL CREATED':human(s.realBnb)+' / '+decimal(settings.threshold)+' BNB TO PANCAKESWAP';$('#market-links').replaceChildren();addLink('GMGN','https://gmgn.ai/bsc/token/'+s.token);if(s.reference?.url)addLink('REFERENCE SOURCE',s.reference.url);if(s.graduated){addLink('PANCAKESWAP','https://pancakeswap.finance/swap?chain=bsc&inputCurrency=BNB&outputCurrency='+s.token);if(s.pool!==E.ZeroAddress)addLink('DEX SCREENER','https://dexscreener.com/bsc/'+s.pool)}$('#asset-note').textContent=s.graduated?'Creator controls LP and can withdraw liquidity. Terminal links do not confirm indexing. Asset references do not guarantee token prices.':'Trading uses the Anything curve. PancakeSwap liquidity is created at graduation. Asset references do not fix token prices or provide redemption rights.';$('#amtu').textContent=side==='buy'?'BNB':s.sym;drawChart()}
function select(token){if(busy||isHiddenToken(token))return;selected=token;const ref=secs.find(s=>s.token===token)?.reference;if(ref)requestQuotes([ref.id]);invalidateQuote();renderSelected();renderTable();recalc();updateBal().catch(()=>{})}
function drawChart(){const cv=$('#gp'),s=secs.find(x=>x.token===selected);if(!s)return;const w=cv.clientWidth,h=cv.clientHeight,dpr=devicePixelRatio||1;if(!w||!h)return;cv.width=w*dpr;cv.height=h*dpr;const c=cv.getContext('2d');c.scale(dpr,dpr);c.clearRect(0,0,w,h);const data=hist[s.token]||[];$('#chart-note').textContent=data.length+' observations · nBNB · since '+new Date(data[0]?.at||Date.now()).toLocaleTimeString('en-GB');if(data.length<2){c.fillStyle='#a85f00';c.font='11px monospace';c.fillText('Collecting actual observations…',12,45);return}const values=data.map(x=>x.price),min=Math.min(...values),max=Math.max(...values),span=max-min||Math.max(max*.02,1),low=max===min?min-span/2:min,high=max===min?max+span/2:max;const X=i=>10+i/(data.length-1)*(w-78),Y=v=>12+(high-v)/(high-low)*(h-30);c.font='9px monospace';for(let i=0;i<5;i++){const val=low+(high-low)*i/4,y=Y(val);c.strokeStyle='#241608';c.beginPath();c.moveTo(10,y);c.lineTo(w-60,y);c.stroke();c.fillStyle='#a85f00';c.fillText(nBNB(val),w-56,y+3)}c.beginPath();data.forEach((d,i)=>i?c.lineTo(X(i),Y(d.price)):c.moveTo(X(i),Y(d.price)));c.strokeStyle='#ff9e1b';c.lineWidth=1.6;c.stroke()}

/* Quotes retain decimal precision and are bound to a specific token, side and amount. */
function updateExecLabel(){const s=secs.find(x=>x.token===selected),b=$('#exec');b.className='exec '+side;if(busy){b.disabled=true;b.textContent='WAITING FOR WALLET / NETWORK';return}if(!me){b.disabled=false;b.textContent='CONNECT WALLET TO TRADE';return}if(pendingHash){b.disabled=true;b.textContent='TRANSACTION PENDING · REFRESH TO CHECK';return}if(!s||s.graduated){b.disabled=true;b.textContent=s?.graduated?'USE PANCAKESWAP LINK ABOVE':'SELECT A TOKEN';return}b.disabled=!quote||quote.expires<Date.now();b.textContent=side==='buy'?'REVIEW & BUY IN WALLET':'REVIEW & SELL IN WALLET'}
function renderQuick(){const q=$('#quick');q.replaceChildren();for(const value of side==='buy'?['0.005','0.01','0.02','0.05']:['25%','50%','100%']){const b=document.createElement('button');b.type='button';b.textContent=value;b.disabled=busy;b.onclick=async()=>{try{if(side==='buy')$('#amt').value=value;else{if(!me||!selected)throw Error('Connect and select a token first.');const balance=await new E.Contract(selected,ERC20_ABI,rpc).balanceOf(me);$('#amt').value=fmt(balance*BigInt(parseInt(value))/100n)}await recalc()}catch(e){status(errorText(e))}};q.append(b)}}
async function recalc(){if(busy)return;invalidateQuote();const version=quoteVersion,s=secs.find(x=>x.token===selected),orderSide=side;$('#i-get').textContent=$('#i-impact').textContent=$('#i-fee').textContent='—';$('#order-note').textContent='';if(!s||s.graduated)return;try{const input=parseAmount($('#amt').value),bps=Number($('#slippage').value);const [p,virtual,feeBps,output]=await Promise.all([pad.getPair(s.token),pad.virtualBnb(),pad.FEE_BPS(),orderSide==='buy'?pad.quoteBuy(s.token,input):pad.quoteSell(s.token,input)]);if(version!==quoteVersion)return;if(p.graduated)throw Error('This token graduated. Refresh and use PancakeSwap.');const calculated=curveQuote({side:orderSide,input,virtualBnb:virtual,realBnb:p.realBnb,tokenReserve:p.tokenReserve,feeBps});const min=minOutput(output,bps);quote={token:s.token,side:orderSide,input,output,min,expires:Date.now()+30000,version,bps};$('#i-get').textContent=human(output)+' '+(orderSide==='buy'?s.sym:'BNB');$('#i-min').textContent=decimal(min)+' '+(orderSide==='buy'?s.sym:'BNB');$('#i-impact').textContent=calculated.impact.toFixed(2)+'%';$('#i-fee').textContent=decimal(calculated.fee)+' BNB';$('#order-note').textContent='Quote valid for 30 seconds. Network fees are additional.'}catch(e){if(version===quoteVersion)$('#order-note').textContent=errorText(e)}updateExecLabel()}
async function executeTrade(){if(!me){openWallet();return}if(busy||pendingHash||!quote)return;const q={...quote},owner=me,writer=padWrite,selectedSigner=signer,s=secs.find(x=>x.token===q.token);setBusy(true);try{await verifyWallet();if(q.expires<Date.now()||q.token!==selected||q.side!==side||q.input!==parseAmount($('#amt').value))throw Error('Quote expired or order changed. Review the refreshed quote.');if(q.side==='sell'){const t=new E.Contract(q.token,ERC20_ABI,selectedSigner);if(await t.balanceOf(owner)<q.input)throw Error('Insufficient token balance.');if(await t.allowance(owner,C.LAUNCHPAD)<q.input){status('Approve only this token amount in your wallet.');await waitMined(await t.approve(C.LAUNCHPAD,q.input),'approval',q.token);await verifyWallet();if(owner!==me)throw Error('Wallet changed after approval.');const fresh=await pad.quoteSell(q.token,q.input);if(fresh<q.min)throw Error('Quote moved beyond your tolerance. Approval completed; review a new quote.')}}
 const current=q.side==='buy'?await pad.quoteBuy(q.token,q.input):await pad.quoteSell(q.token,q.input);if(current<q.min)throw Error('Price moved beyond your tolerance. Review a new quote.');await verifyWallet();if(owner!==me)throw Error('Wallet changed.');status('Confirm '+q.side+' in your wallet. Minimum receive: '+decimal(q.min)+' '+(q.side==='buy'?s.sym:'BNB'));const tx=q.side==='buy'?await writer.buy(q.token,q.min,{value:q.input}):await writer.sell(q.token,q.input,q.min);await waitMined(tx,q.side,q.token);status(q.side.toUpperCase()+' CONFIRMED · '+s.sym,tx.hash);await loadSecurities();await updateBal()}catch(e){status(errorText(e),pendingHash||undefined)}finally{setBusy(false);await recalc()}}

/* Creation uses the already deployed contract. It never redeploys the launchpad. */
async function prepareLaunch(){if(!me){openWallet();return}if(busy||pendingHash)return;invalidateLaunch();setBusy(true);try{await verifyWallet();await requirePricedReference($('#f-feed').value);const rewardIntent=await rewards.launchIntent();const fields=validTokenFields($('#f-name').value,$('#f-ticker').value.trim().toUpperCase()),firstBuy=parseAmount($('#f-buy').value.trim()||'0',{allowZero:true}),choice=launchChoice(),{asset,feedId}=choice;const [fee,threshold,virtual,feeBps]=await Promise.all([pad.creationFee(),pad.graduationThreshold(),pad.virtualBnb(),pad.FEE_BPS()]);const value=fee+firstBuy,args=[fields.name,fields.symbol,asset,feedId,firstBuy];const gas=await padWrite.createPair.estimateGas(...args,{value}),fees=await browserProvider.getFeeData();if(!fees.gasPrice)throw Error('Network fee unavailable. Try again.');const gasLimit=(gas*125n+99n)/100n,gasCost=gasLimit*fees.gasPrice;if(await rpc.getBalance(me,'pending')<value+gasCost)throw Error('Need up to '+decimal(value+gasCost)+' BNB including the gas limit.');launchReview={...fields,rewardIntent,referenceId:choice.id,args,value,firstBuy,fee,threshold,virtual,feeBps,gasLimit,gasPrice:fees.gasPrice,owner:me,expires:Date.now()+120000};const estimated=firstBuy?curveQuote({side:'buy',input:firstBuy,virtualBnb:virtual,realBnb:0n,tokenReserve:800000000n*10n**18n,feeBps}).out:0n;$('#launch-review').replaceChildren();for(const text of [fields.name+' / '+fields.symbol,...(rewardIntent?['After creation: separately fund '+rewardIntent.amount+' USDT for '+rewardIntent.days+' days. Approval and funding need additional BNB fees. Token creation succeeds independently of reward funding.']:[]),'Asset reference: '+choice.label+' · token price trades independently','Network: '+(LOCAL?'LOCAL FORK · TEST FUNDS':'BNB Chain · MAINNET'),'Creator / LP recipient: '+me,'Creation fee: '+decimal(fee)+' BNB','First buy: '+decimal(firstBuy)+' BNB · estimated '+human(estimated)+' tokens','Network fee limit: '+decimal(gasCost)+' BNB','Maximum total at this gas price: '+decimal(value+gasCost)+' BNB','Graduation: '+decimal(threshold)+' BNB on the curve. LP is withdrawable by the creator.','The deployed contract has no minimum-output parameter for a first buy. Ordinary buy/sell orders use your slippage setting.']){const p=document.createElement('p');p.textContent=text;$('#launch-review').append(p)}$('#launch-review').hidden=false;$('#f-confirm').hidden=false;$('#f-status').textContent='Review valid for two minutes. No transaction has been sent.'}catch(e){$('#f-status').textContent=errorText(e)}finally{setBusy(false)}}
async function confirmLaunch(){if(busy||!launchReview||pendingHash)return;const r=launchReview,writer=padWrite;setBusy(true);try{await verifyWallet();if(r.expires<Date.now()||r.owner!==me)throw Error('Review expired or wallet changed. Review the launch again.');await requirePricedReference(r.referenceId);const [fee,threshold,virtual]=await Promise.all([pad.creationFee(),pad.graduationThreshold(),pad.virtualBnb()]);if(fee!==r.fee||threshold!==r.threshold||virtual!==r.virtual)throw Error('Launchpad settings changed. Review the launch again.');$('#f-status').textContent='Confirm the token launch in your wallet.';const tx=await writer.createPair(...r.args,{value:r.value,gasLimit:r.gasLimit,gasPrice:r.gasPrice});$('#f-status').textContent='Sent: '+tx.hash;const receipt=await waitMined(tx,'launch');const event=receipt.logs.filter(l=>l.address.toLowerCase()===C.LAUNCHPAD.toLowerCase()).map(l=>{try{return pad.interface.parseLog(l)}catch{return null}}).find(e=>e?.name==='PairCreated'&&e.args.creator.toLowerCase()===r.owner.toLowerCase());if(!event)throw Error('Transaction confirmed, but the creation event was not found. Check the receipt.');await loadSecurities();selected=event.args.token;renderSelected();renderTable();await updateBal();$('#ovl').classList.remove('on');invalidateLaunch();status('Token created: '+r.symbol+(r.rewardIntent?' · USDT reward funding is still required.':''),receipt.hash);if(r.rewardIntent){setBusy(false);rewards.created(event.args.token,r.rewardIntent)}}catch(e){$('#f-status').textContent=errorText(e);status(errorText(e),pendingHash||undefined);launchReview=null;$('#f-confirm').hidden=true}finally{setBusy(false);await recalc()}}
async function refresh(manual=false){if(polling||busy)return;polling=true;try{await loadSettings();await loadFeeds();await loadSecurities();if(me){await updateBal();if(manual)await recoverPending()}await recalc();if(manual&&!pendingHash)status('Refreshed from BNB Chain.')}catch(e){status('Refresh failed; displayed data may be old. '+errorText(e))}finally{polling=false}}
async function boot(){try{if(LOCAL){const response=await fetch('/__qa_config');if(!response.ok)throw Error('Local test server unavailable');const local=await response.json();C.RPC_URL=local.rpc;if(local.rewards)C.REWARDS=local.rewards;if(local.usdt)C.USDT=local.usdt;if(local.launchpad)C.LAUNCHPAD=local.launchpad;if(local.oracle)C.ORACLE=local.oracle;if(local.router)C.ROUTER=local.router;$('#st-chain').textContent='LOCAL FORK · TEST FUNDS';$('#netlbl').textContent='CONNECT TEST WALLET'}const request=new E.FetchRequest(C.RPC_URL);request.timeout=15000;rpc=new E.JsonRpcProvider(request,C.CHAIN_ID,{staticNetwork:true,cacheTimeout:-1});rpc.pollingInterval=1000;if(Number(await rpc.send('eth_chainId',[]))!==C.CHAIN_ID)throw Error('Read RPC is connected to the wrong chain.');pad=new E.Contract(C.LAUNCHPAD,PAD_ABI,rpc);oracle=new E.Contract(C.ORACLE,ORACLE_ABI,rpc);const [oracleAddress,routerAddress]=await Promise.all([pad.oracle(),pad.router()]);if(E.getAddress(oracleAddress)!==E.getAddress(C.ORACLE)||E.getAddress(routerAddress)!==E.getAddress(LOCAL&&C.ROUTER?C.ROUTER:'0x10ED43C718714eb63d5aA57B78B54704E256024E'))throw Error('Launchpad configuration mismatch.');router=new E.Contract(routerAddress,['function factory() view returns(address)','function WETH() view returns(address)'],rpc);const [factoryAddress,w]=await Promise.all([router.factory(),router.WETH()]);wrapped=w;factory=new E.Contract(factoryAddress,['function getPair(address,address) view returns(address)'],rpc);await loadSettings();await loadFeeds();await loadSecurities();renderQuick();await recalc();$('#boot').style.display='none';status(LOCAL?'LOCAL FORK · No real funds or mainnet transactions.':'Connected to BNB Chain · '+secs.length+' tokens');clearInterval(timer);timer=setInterval(()=>refresh(),15000);clearInterval(clockTimer);clockTimer=setInterval(()=>{$('#clock').textContent=new Date().toLocaleTimeString('en-GB');updateExecLabel()},1000);discover();rewards.ready()}catch(e){$('#boot').style.display='flex';$('#bootmsg').replaceChildren(document.createTextNode('CONNECTION FAILED: '+errorText(e)));const b=document.createElement('button');b.className='boot-retry';b.textContent='RETRY';b.onclick=()=>{b.remove();boot()};$('#bootmsg').append(document.createElement('br'),b)}}
$('#netbtn').onclick=openWallet;$('#wallet-close').onclick=()=>$('#wallet-dialog').close();$('#fk-about').onclick=()=>$('#about-dialog').showModal();$('#about-close').onclick=()=>$('#about-dialog').close();$('#fk-refresh').onclick=()=>refresh(true);$('#fk-launch').onclick=()=>openLaunch();$('#mclose').onclick=()=>{if(!busy)$('#ovl').classList.remove('on')};$('#ovl').onclick=e=>{if(e.target===$('#ovl')&&!busy)$('#ovl').classList.remove('on')};$('#fk-markets').onclick=()=>$('.tbl-wrap').scrollIntoView({behavior:'smooth'});$('#fk-chart').onclick=()=>$('.chart-pane').scrollIntoView({behavior:'smooth'});$('#fk-trade').onclick=()=>{$('.trade').scrollIntoView({behavior:'smooth'});$('#amt').focus()};
for(const direction of ['buy','sell'])$('#tab-'+direction).onclick=()=>{if(busy)return;side=direction;$('#tab-buy').classList.toggle('on',side==='buy');$('#tab-sell').classList.toggle('on',side==='sell');$('#amt').value=side==='buy'?'0.01':'1000000';renderSelected();renderQuick();recalc()};
$('#amt').oninput=recalc;$('#slippage').onchange=recalc;$('#exec').onclick=executeTrade;$('#f-deploy').onclick=prepareLaunch;$('#f-confirm').onclick=confirmLaunch;for(const id of ['#f-name','#f-ticker','#f-buy'])$(id).oninput=invalidateLaunch;$('#f-feed').onchange=()=>{invalidateLaunch();feedDetail()};window.addEventListener('resize',drawChart);window.addEventListener('pagehide',()=>{clearInterval(timer);clearInterval(clockTimer)});window.addEventListener('pageshow',e=>{if(e.persisted)location.reload()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!busy)$('#ovl').classList.remove('on')});
rewards=initRewards({get:()=>({rpc,signer,me,C,selected,secs,LOCAL,busy,pendingHash}),verifyWallet,waitMined,setBusy,status,errorText,openWallet,quote:async asset=>{if(asset.provider==='oracle')return oracleQuote(asset);await requestQuotes([asset.id]);return assetQuote(asset.id)}});
$('#f-rewards').onchange=()=>{invalidateLaunch();$('#f-reward-fields').hidden=!$('#f-rewards').checked};$('#f-reward-budget').oninput=invalidateLaunch;$('#f-reward-days').onchange=invalidateLaunch;
initCatalogue({onChoose:openLaunch,onSelectionChange:()=>{invalidateLaunch();feedDetail()},isBusy:()=>busy,oracleQuote,onQuotes:()=>{feedDetail();renderSelected()}});$('#create-token').onclick=()=>openLaunch();$('#token-expand').onclick=()=>{const expanded=$('#my-tokens').classList.toggle('expanded');$('#token-expand').textContent=expanded?'Collapse ↕':'Expand ↕';$('#token-expand').setAttribute('aria-expanded',expanded)};$('#token-scope').onclick=()=>{if(busy)return;marketScope=marketScope==='mine'?'all':'mine';$('#token-scope').textContent=marketScope==='mine'?'Browse all':'My tokens';$('#my-tokens .pane-h>span:first-child').innerHTML=marketScope==='mine'?'<span class="code">YOU</span>MY TOKENS':'<span class="code">MKTS</span>ALL MARKETS';renderTable();if(marketScope==='all'&&!selected&&secs.length)select(secs[0].token)};renderTable();$('#boot').style.display='none';boot();
