import {englishError} from './lib/language.mjs';
import {USDT,TOKEN_ABI,runtimeMatches,verifyRewards} from './lib/rewards.mjs';
import {FLAP_PORTAL} from './lib/flap.mjs';
const E=window.ethers,C={...window.ANYPAIR_CONFIG},$=s=>document.querySelector(s),wallets=[];
const local=['localhost','127.0.0.1'].includes(location.hostname)&&new URLSearchParams(location.search).get('qa')==='1';
let rpc,artifacts,provider,injected,signer,owner,review,busy=false,ready=false;
const key='anything:flap-deployment:56';
const status=text=>{$('#setup-status').textContent=text};
function invalidate(){review=null;$('#setup-deploy').hidden=true;$('#setup-review-text').hidden=true;}
function txLink(hash){const a=document.createElement('a');a.href=C.EXPLORER+'/tx/'+hash;a.textContent='View deployment transaction ↗';a.target='_blank';a.rel='noopener noreferrer';$('#setup-result').replaceChildren(a);}
async function verify(){if(!signer)throw Error('Connect a wallet.');if(local)return;const [chain,accounts]=await Promise.all([injected.request({method:'eth_chainId'}),injected.request({method:'eth_accounts'})]);if(Number(chain)!==56||accounts[0]?.toLowerCase()!==owner.toLowerCase())throw Error('Wallet changed. Connect and review again.');}
async function connect(p){if(busy||!ready)return;try{invalidate();injected=p;if(local)provider=rpc;else{await p.request({method:'eth_requestAccounts'});if(Number(await p.request({method:'eth_chainId'}))!==56)await p.request({method:'wallet_switchEthereumChain',params:[{chainId:'0x38'}]});provider=new E.BrowserProvider(p,undefined,{cacheTimeout:-1});}signer=await provider.getSigner();owner=await signer.getAddress();await verify();p?.on?.('accountsChanged',invalidate);p?.on?.('chainChanged',invalidate);$('#setup-review').disabled=false;status('Connected: '+owner);}catch(e){signer=null;$('#setup-review').disabled=true;status(englishError(e));}}
function add(d){if(!d?.provider||wallets.some(w=>w.provider===d.provider))return;wallets.push(d);const b=document.createElement('button');b.textContent='Connect '+String(d.info?.name||'wallet').slice(0,80);b.onclick=()=>connect(d.provider);$('#setup-wallets').append(b);}
window.addEventListener('eip6963:announceProvider',e=>add(e.detail));
async function result(address,hash){
 const deployment=new E.Contract(address,artifacts.deployment.abi,rpc);if(!runtimeMatches(await rpc.getCode(address),artifacts.deployment))throw Error('Deployment bytecode mismatch.');
 const [gateway,rewards]=await Promise.all([deployment.gateway(),deployment.rewards()]);const g=new E.Contract(gateway,artifacts.gateway.abi,rpc);
 if(!runtimeMatches(await rpc.getCode(gateway),artifacts.gateway)||(await g.portal()).toLowerCase()!==FLAP_PORTAL.toLowerCase())throw Error('Gateway verification failed.');
 await verifyRewards(E,rpc,{...C,LAUNCHPAD:gateway,REWARDS:rewards},artifacts.rewards);
 txLink(hash);const pre=document.createElement('pre');pre.textContent='Deployment: '+address+'\nGateway: '+gateway+'\nRewards: '+rewards;$('#setup-result').append(pre);const b=document.createElement('button');b.textContent='COPY DEPLOYMENT ADDRESS';b.onclick=()=>navigator.clipboard.writeText(address).then(()=>status('Address copied.'));$('#setup-result').append(b);status('Deployment confirmed. Gateway and reward vault bytecode verified. Send the deployment address to activate the site.');ready=false;$('#setup-review').disabled=true;$('#setup-deploy').hidden=true;
}
async function recover(){let saved;try{saved=JSON.parse(localStorage.getItem(key)||'null')}catch{}if(!saved?.hash)return false;txLink(saved.hash);const r=await rpc.getTransactionReceipt(saved.hash);if(r?.status===1&&r.contractAddress){await result(r.contractAddress,saved.hash);return true;}if(r?.status===0){localStorage.removeItem(key);return false;}ready=false;status('Deployment is pending or replaced. Check wallet activity, then reload this page. Do not deploy twice.');return true;}
$('#setup-review').onclick=async()=>{if(busy||!ready||!signer)return;busy=true;$('#setup-review').disabled=true;try{invalidate();await verify();if(await recover())return;const f=new E.ContractFactory(artifacts.deployment.abi,artifacts.deployment.bytecode,signer),tx=await f.getDeployTransaction(FLAP_PORTAL,C.USDT),gas=await signer.estimateGas(tx),fees=await provider.getFeeData();if(!fees.gasPrice)throw Error('Gas price unavailable.');const gasLimit=(gas*130n+99n)/100n,cost=gasLimit*fees.gasPrice;if(await rpc.getBalance(owner)<cost)throw Error('Need up to '+E.formatEther(cost)+' BNB for network fees.');review={owner,gasLimit,gasPrice:fees.gasPrice,expires:Date.now()+120000};$('#setup-review-text').textContent='Network: '+(local?'LOCAL TEST CHAIN':'BNB Chain · MAINNET')+'\nSigner: '+owner+'\nFlap Portal: '+FLAP_PORTAL+'\nUSDT: '+C.USDT+'\nMaximum network fee at this gas price: '+E.formatEther(cost)+' BNB\nUSDT transferred: 0\nTokens launched: 0\nReview expires in two minutes.';$('#setup-review-text').hidden=false;$('#setup-deploy').hidden=false;status('Review the deployment, then confirm in your wallet.');}catch(e){status(englishError(e));}finally{busy=false;$('#setup-review').disabled=!ready;}};
$('#setup-deploy').onclick=async()=>{if(busy||!ready||!review)return;busy=true;$('#setup-deploy').disabled=true;$('#setup-review').disabled=true;try{await verify();if(review.owner!==owner||review.expires<Date.now())throw Error('Review expired. Review again.');if(await recover())return;status('Confirm deployment in your wallet.');const f=new E.ContractFactory(artifacts.deployment.abi,artifacts.deployment.bytecode,signer),c=await f.deploy(FLAP_PORTAL,C.USDT,{gasLimit:review.gasLimit,gasPrice:review.gasPrice}),tx=c.deploymentTransaction();localStorage.setItem(key,JSON.stringify({hash:tx.hash}));ready=false;txLink(tx.hash);let receipt;try{receipt=await tx.wait(1,120000);}catch(e){if(e.code!=='TRANSACTION_REPLACED')throw e;if(e.cancelled){localStorage.removeItem(key);ready=true;invalidate();throw Error('Deployment cancelled.');}receipt=e.receipt;localStorage.setItem(key,JSON.stringify({hash:receipt.hash}));}if(!receipt?.contractAddress||receipt.status!==1)throw Error('Deployment not confirmed. Check the transaction.');await result(receipt.contractAddress,receipt.hash);}catch(e){status(englishError(e));}finally{busy=false;$('#setup-deploy').disabled=!ready;$('#setup-review').disabled=!ready;}};
try{
 if(local){const q=await(await fetch('/__qa_config')).json();C.RPC_URL=q.rpc;C.USDT=q.usdt||C.USDT;C.FLAP_GATEWAY=null;}
 if(!local&&(C.CHAIN_ID!==56||C.USDT.toLowerCase()!==USDT))throw Error('Unexpected network or USDT address.');
 rpc=new E.JsonRpcProvider(C.RPC_URL,56,{staticNetwork:true,cacheTimeout:-1});rpc.pollingInterval=1000;if(Number(await rpc.send('eth_chainId',[]))!==56)throw Error('Wrong RPC network.');
 artifacts=await(await fetch('/assets/flap-artifacts.json')).json();for(const a of Object.values(artifacts))if(E.keccak256(a.bytecode)!==a.bytecodeHash)throw Error('Build hash mismatch.');
 if(await rpc.getCode(FLAP_PORTAL)==='0x')throw Error('Flap Portal unavailable.');const usd=new E.Contract(C.USDT,TOKEN_ABI,rpc);if(await usd.decimals()!==18n||await usd.symbol()!=='USDT')throw Error('USDT verification failed.');
 $('#setup-config').textContent='BNB CHAIN · 56\nFlap Portal: '+FLAP_PORTAL+'\nUSDT: '+C.USDT+'\nBuild: '+artifacts.deployment.bytecodeHash;
 if(C.FLAP_GATEWAY)status('Flap gateway already configured: '+C.FLAP_GATEWAY);
 else if(!await recover()){ready=true;if(local){const b=document.createElement('button');b.textContent='Connect LOCAL TEST wallet';b.onclick=()=>connect(null);$('#setup-wallets').append(b);}else{window.dispatchEvent(new Event('eip6963:requestProvider'));if(window.ethereum)for(const provider of window.ethereum.providers||[window.ethereum])add({provider,info:{name:'browser wallet'}});}status('Connect a wallet to review deployment.');}
}catch(e){status(englishError(e));}
