import {USDT,TOKEN_ABI,verifyRewards} from './lib/rewards.mjs';
const E=window.ethers,C={...window.ANYPAIR_CONFIG},$=s=>document.querySelector(s),wallets=[];
const local=['localhost','127.0.0.1'].includes(location.hostname)&&new URLSearchParams(location.search).get('qa')==='1';
let rpc,artifact,provider,injected,signer,owner,review,busy=false,ready=false;
const key='anything:rewards-deployment:'+C.CHAIN_ID+':'+C.LAUNCHPAD.toLowerCase();
function status(s){$('#setup-status').textContent=s;}
function fail(e){status(e.code==='ACTION_REJECTED'||e.code===4001?'Request declined.':String(e.shortMessage||e.message||e).slice(0,500));}
function txLink(hash){const a=document.createElement('a');a.href=C.EXPLORER+'/tx/'+hash;a.textContent='View deployment transaction ↗';a.target='_blank';a.rel='noopener noreferrer';$('#setup-result').replaceChildren(a);}
function invalidate(){review=null;$('#setup-deploy').hidden=true;$('#setup-review-text').hidden=true;}
function add(detail){if(!detail?.provider||wallets.some(w=>w.provider===detail.provider))return;wallets.push(detail);const b=document.createElement('button');b.textContent='Connect '+String(detail.info?.name||'wallet').slice(0,80);b.onclick=()=>connect(detail.provider);$('#setup-wallets').append(b);}
window.addEventListener('eip6963:announceProvider',e=>add(e.detail));
async function verify(){if(!signer)throw Error('Connect a wallet.');if(local)return;const [chain,accounts]=await Promise.all([injected.request({method:'eth_chainId'}),injected.request({method:'eth_accounts'})]);if(Number(chain)!==56||!accounts[0]||accounts[0].toLowerCase()!==owner.toLowerCase())throw Error('Wallet account or network changed. Reconnect and review again.');}
async function connect(p){if(busy||!ready)return;try{invalidate();if(injected){injected.removeListener?.('accountsChanged',invalidate);injected.removeListener?.('chainChanged',invalidate);}injected=p;if(local)provider=rpc;else{await p.request({method:'eth_requestAccounts'});if(Number(await p.request({method:'eth_chainId'}))!==56)await p.request({method:'wallet_switchEthereumChain',params:[{chainId:'0x38'}]});provider=new E.BrowserProvider(p,undefined,{cacheTimeout:-1});}signer=await provider.getSigner();owner=await signer.getAddress();await verify();injected?.on?.('accountsChanged',invalidate);injected?.on?.('chainChanged',invalidate);$('#setup-review').disabled=false;status('Connected: '+owner);}catch(e){signer=null;$('#setup-review').disabled=true;fail(e);}}
async function result(address,hash){await verifyRewards(E,rpc,{...C,REWARDS:address},artifact);txLink(hash);const p=document.createElement('p');p.textContent='Deployment confirmed and bytecode checked. Rewards address:';const pre=document.createElement('pre');pre.textContent=address;$('#setup-result').append(p,pre);const b=document.createElement('button');b.textContent='COPY ADDRESS';b.onclick=()=>navigator.clipboard.writeText(address).then(()=>status('Address copied.'));$('#setup-result').append(b);status('Send this address to activate the website configuration. No reward campaign has been funded yet.');$('#setup-review').disabled=true;$('#setup-deploy').hidden=true;ready=false;}
async function recover(){let r;try{r=JSON.parse(localStorage.getItem(key)||'null')}catch{}if(!r?.hash)return false;txLink(r.hash);const receipt=await rpc.getTransactionReceipt(r.hash);if(receipt?.status===1&&receipt.contractAddress){await result(receipt.contractAddress,r.hash);return true;}if(receipt?.status===0){localStorage.removeItem(key);status('The previous deployment failed. You may review a new one.');return false;}ready=false;status('Deployment confirmation is pending or the transaction was replaced. Check wallet activity. Reload this page after confirmation; do not deploy twice.');return true;}
$('#setup-review').onclick=async()=>{if(busy||!ready||!signer)return;busy=true;$('#setup-review').disabled=true;try{invalidate();await verify();if(await recover())return;const factory=new E.ContractFactory(artifact.abi,artifact.bytecode,signer),tx=await factory.getDeployTransaction(C.LAUNCHPAD,C.USDT),gas=await signer.estimateGas(tx),fees=await provider.getFeeData();if(!fees.gasPrice)throw Error('Network gas price unavailable.');const gasLimit=(gas*125n+99n)/100n,cost=gasLimit*fees.gasPrice;if(await rpc.getBalance(owner)<cost)throw Error('Need up to '+E.formatEther(cost)+' BNB for network fees.');review={owner,gasLimit,gasPrice:fees.gasPrice,expires:Date.now()+120000};$('#setup-review-text').textContent='Network: '+(local?'LOCAL TEST CHAIN':'BNB Smart Chain · MAINNET')+'\nSigner: '+owner+'\nLaunchpad: '+C.LAUNCHPAD+'\nUSDT: '+C.USDT+'\nMaximum network fee at this gas price: '+E.formatEther(cost)+' BNB\nUSDT transferred: 0\nReview expires in two minutes.';$('#setup-review-text').hidden=false;$('#setup-deploy').hidden=false;status('Review the addresses and network fee, then confirm deployment in your wallet.');}catch(e){fail(e);}finally{busy=false;$('#setup-review').disabled=!ready;}};
$('#setup-deploy').onclick=async()=>{if(busy||!ready||!review)return;busy=true;$('#setup-deploy').disabled=true;$('#setup-review').disabled=true;try{await verify();if(review.owner!==owner||review.expires<Date.now())throw Error('Review expired. Review again.');if(await recover())return;const factory=new E.ContractFactory(artifact.abi,artifact.bytecode,signer);status('Confirm the deployment transaction in your wallet.');const contract=await factory.deploy(C.LAUNCHPAD,C.USDT,{gasLimit:review.gasLimit,gasPrice:review.gasPrice}),tx=contract.deploymentTransaction();try{localStorage.setItem(key,JSON.stringify({hash:tx.hash,from:owner,nonce:tx.nonce}));}catch{}ready=false;txLink(tx.hash);status('Deployment sent. Waiting for confirmation.');let receipt;try{receipt=await tx.wait(1,120000);}catch(e){if(e.code!=='TRANSACTION_REPLACED')throw e;if(e.cancelled){localStorage.removeItem(key);ready=true;invalidate();throw Error('Deployment cancelled in your wallet. Review again if you want to deploy.');}receipt=e.receipt;localStorage.setItem(key,JSON.stringify({hash:receipt.hash,from:owner}));}if(!receipt||receipt.status!==1||!receipt.contractAddress)throw Error('Deployment not confirmed. Check the transaction before trying again.');await result(receipt.contractAddress,receipt.hash);}catch(e){fail(e);}finally{busy=false;$('#setup-deploy').disabled=!ready;$('#setup-review').disabled=!ready;}};
try{
 if(local){const r=await fetch('/__qa_config'),q=await r.json();C.RPC_URL=q.rpc;C.USDT=q.usdt;C.LAUNCHPAD=q.launchpad||C.LAUNCHPAD;C.REWARDS=null;}
 if(!local&&(C.CHAIN_ID!==56||C.USDT.toLowerCase()!==USDT))throw Error('Unexpected production network or USDT address.');
 rpc=new E.JsonRpcProvider(C.RPC_URL,56,{staticNetwork:true,cacheTimeout:-1});rpc.pollingInterval=1000;
 if(Number(await rpc.send('eth_chainId',[]))!==56)throw Error('Wrong RPC network.');
 const r=await fetch('/assets/rewards-artifact.json');if(!r.ok)throw Error('Build unavailable.');artifact=await r.json();if(E.keccak256(artifact.bytecode)!==artifact.bytecodeHash)throw Error('Build hash mismatch.');
 const usd=new E.Contract(C.USDT,TOKEN_ABI,rpc);if(await usd.decimals()!==18n||await usd.symbol()!=='USDT'||await rpc.getCode(C.LAUNCHPAD)==='0x')throw Error('Contract configuration verification failed.');
 $('#setup-config').textContent=(local?'LOCAL TEST FUNDS':'BNB SMART CHAIN · CHAIN 56')+'\nLaunchpad: '+C.LAUNCHPAD+'\nUSDT: '+C.USDT+'\nBuild: '+artifact.bytecodeHash;
 if(C.REWARDS){await verifyRewards(E,rpc,C,artifact);status('Rewards are already activated: '+C.REWARDS);}
 else if(!await recover()){ready=true;if(local){const b=document.createElement('button');b.textContent='Connect LOCAL TEST wallet';b.onclick=()=>connect(null);$('#setup-wallets').append(b);}else{window.dispatchEvent(new Event('eip6963:requestProvider'));if(window.ethereum)for(const p of window.ethereum.providers||[window.ethereum])add({provider:p,info:{name:'browser wallet'}});status('Connect a browser wallet on BNB Chain to review deployment.');}}
}catch(e){fail(e);}
