import {test} from 'node:test';import assert from 'node:assert/strict';
import {ipfsURL} from '../lib/flap.mjs';import {createUploadHandler} from '../api/flap-upload.js';
const cid='bafkreieepx7lh6zcpqsneo2jdeqmcgxjg7facam34w5ezh4myajjauuc24';
const avatar='data:image/webp;base64,'+Buffer.from('RIFF'+String.fromCharCode(16,0,0,0)+'WEBP'+'test-data').toString('base64');
const request=()=>({method:'POST',headers:{'content-type':'application/json'},body:{creator:'0x'+'11'.repeat(20),token:'0x'+'22'.repeat(20),reference:'bigmac-usa',profile:{avatar,description:'Burger reference',x:'@burger'}}});
const response=()=>({headers:{},statusCode:200,setHeader(k,v){this.headers[k]=v},end(v){this.body=JSON.parse(v)}});
test('IPFS identifiers cannot turn into arbitrary external hosts or paths',()=>{assert.equal(ipfsURL('ipfs://'+cid),'https://flap.mypinata.cloud/ipfs/'+cid);for(const bad of ['https://evil.test/a','../../etc/passwd',cid+'/../x','',null])assert.throws(()=>ipfsURL(bad));});
test('profile upload sends public profile, creator and reference to fixed Flap gateway',async()=>{let called=false;const res=response();await createUploadHandler(async(url,options)=>{called=true;assert.equal(url,'https://funcs.flap.sh/api/upload');const meta=JSON.parse(options.body.get('operations')).variables.meta;assert.equal(meta.creator,request().body.creator);assert.equal(meta.twitter,'https://x.com/burger');assert.match(meta.description,/no price peg/);assert.equal(new URL(meta.website).searchParams.get('reference'),'bigmac-usa');assert.equal(options.body.get('0').type,'image/webp');return{ok:true,json:async()=>({data:{create:cid}})};})(request(),res);assert.ok(called);assert.equal(res.body.cid,cid);});
test('upload validates payload and fails closed when Flap rejects metadata',async()=>{for(const update of [{profile:{}},{token:'not-an-address'},{reference:'nonexistent'}]){const req=request();Object.assign(req.body,update);const res=response();await createUploadHandler(()=>{throw Error('Should not call upstream')})(req,res);assert.equal(res.statusCode,400);}const res=response();await createUploadHandler(async()=>({ok:true,json:async()=>({errors:[{message:'No'}]})}))(request(),res);assert.equal(res.statusCode,502);assert.match(res.body.error,/No token transaction/);});
