import {test} from 'node:test';import assert from 'node:assert/strict';
import {parseAmount,minOutput,curveQuote,feedStatus,escapeHTML,validTokenFields,WAD} from '../lib/market.mjs';
test('decimal amounts preserve wei, reject ambiguous or malformed input',()=>{assert.equal(parseAmount('0.000000000000000001'),1n);assert.equal(parseAmount('9007199254740993'),9007199254740993n*WAD);assert.equal(parseAmount('0',{allowZero:true}),0n);for(const s of ['0','-1','1e-3','NaN','1.2foo','1,2','.1','1.1234567890123456789'])assert.throws(()=>parseAmount(s));});
test('minimum output enforces selected tolerance and cannot collapse to zero',()=>{assert.equal(minOutput(100000n,100),99000n);assert.equal(minOutput(100000n,50),99500n);assert.throws(()=>minOutput(1n,100));assert.throws(()=>minOutput(0n,100));assert.throws(()=>minOutput(100n,10000));});
test('curve roundtrip fees and reserves agree at wei precision',()=>{const v=parseAmount('.05'.replace('.','0.')),y=800000000n*WAD,input=parseAmount('0.01');const buy=curveQuote({side:'buy',input,virtualBnb:v,realBnb:0n,tokenReserve:y,feeBps:100n});const net=input-buy.fee;assert.equal(buy.out,y*net/(v+net));assert.equal(buy.fee,100000000000000n);assert.ok(buy.impact>19&&buy.impact<20);const sell=curveQuote({side:'sell',input:buy.out,virtualBnb:v,realBnb:net,tokenReserve:y-buy.out,feeBps:100n});assert.ok(sell.out<input);assert.ok(sell.out+sell.fee<=net);});
test('impossible sales fail instead of presenting a zero executable quote',()=>{assert.throws(()=>curveQuote({side:'sell',input:WAD,virtualBnb:WAD,realBnb:0n,tokenReserve:WAD,feeBps:100n}));});
test('oracle timestamps distinguish stale, fresh, missing and future data',()=>{assert.equal(feedStatus(100,60,160),'RECENT');assert.equal(feedStatus(100,60,161),'STALE');assert.equal(feedStatus(0,60,160),'NO PRICE');assert.equal(feedStatus(200,60,160),'INVALID TIME');});
test('untrusted on-chain names are escaped before HTML templates',()=>{assert.equal(escapeHTML('<img src=x onerror="alert(1)">&'), '&lt;img src=x onerror=&quot;alert(1)&quot;&gt;&amp;');assert.equal(escapeHTML("'"),'&#39;');});
test('token metadata validation rejects missing and malformed fields',()=>{assert.deepEqual(validTokenFields(' Coal ','COAL'),{name:'Coal',symbol:'COAL'});assert.throws(()=>validTokenFields('','COAL'));assert.throws(()=>validTokenFields('Coal','<img>'));assert.throws(()=>validTokenFields('я'.repeat(33),'COAL'));});
