import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {rewardGasLimit,fundingInput,emitted,couponEquivalent,runtimeMatches} from '../lib/rewards.mjs';
const W=10n**18n,now=Date.parse('2026-09-19T10:00:00Z'),date=new Date(now).toISOString(),asset={provider:'yahoo'},q={value:3,currency:'USD',asOf:date,status:'latest market quote'},rate={value:1,currency:'USD',asOf:date};
test('coupon estimate converts USDT through USD and preserves fractional units',()=>{assert.equal(couponEquivalent(6n*W,asset,q,rate,now).units,2n*W);assert.equal(couponEquivalent(6n*W,asset,q,{...rate,value:0.9},now).units,1800000000000000000n);assert.equal(couponEquivalent(1n,asset,q,rate,now).units,0n);assert.equal(couponEquivalent(1234567890123456789012345n,asset,{...q,value:1},rate,now).units,1234567890123456789012345n);});
test('fictional, stale, non-USD and invalid quotes do not invent coupons',()=>{for(const bad of [{...q,value:0},{...q,value:NaN},{...q,currency:'POINTS'},{...q,currency:'EUR'},{...q,status:'STALE'},{...q,asOf:'2020-01-01'},{...q,asOf:'2030-01-01'}])assert.equal(couponEquivalent(W,asset,bad,rate,now),null);for(const provider of ['meme','manual'])assert.equal(couponEquivalent(W,{provider},q,rate,now),null);assert.equal(couponEquivalent(W,asset,q,undefined,now),null);assert.equal(couponEquivalent(W,asset,q,{...rate,asOf:'2026-09-19T09:49:00Z'},now),null);});
test('published food survey is explicitly an older published-price estimate',()=>{const result=couponEquivalent(6n*W,{provider:'bigmac'},{...q,status:'published survey',asOf:'2025-01-01'},rate,now);assert.equal(result.units,2n*W);assert.equal(result.survey,true);});
test('funding rejects oversize budgets and durations while preserving wei',()=>{assert.deepEqual(fundingInput('0.000000000000000001','7'),{budget:1n,duration:604800});for(const a of ['0','-1','1e4','1000000000001'])assert.throws(()=>fundingInput(a,'7'));for(const d of ['0','366','NaN','Infinity'])assert.throws(()=>fundingInput('100',d));});
test('emission stops at the deadline and supports tiny budgets',()=>{const p={start:100n,finish:200n,epochBudget:7n};assert.equal(emitted(p,100),0n);assert.equal(emitted(p,150),3n);assert.equal(emitted(p,500),7n);assert.equal(emitted({...p,finish:0n},150),0n);});
test('runtime verifier accepts only immutable differences and rejects altered executable code',()=>{const a=JSON.parse(fs.readFileSync(new URL('../assets/rewards-artifact.json',import.meta.url)));assert.ok(runtimeMatches(a.deployedBytecode,a));const {start,length}=Object.values(a.immutableReferences)[0][0];let code=a.deployedBytecode;for(const r of Object.values(a.immutableReferences)[0])code=code.slice(0,2+r.start*2)+'a'.repeat(r.length*2)+code.slice(2+(r.start+r.length)*2);assert.ok(runtimeMatches(code,a));const mixed=code.slice(0,2+start*2)+'b'.repeat(length*2)+code.slice(2+(start+length)*2);assert.equal(runtimeMatches(mixed,a),false);assert.equal(runtimeMatches('0x00'+a.deployedBytecode.slice(4),a),false);assert.equal(runtimeMatches('0x',a),false);});

test("gas limit includes additional time-dependent storage writes",()=>{assert.equal(rewardGasLimit(100000n),230000n);assert.ok(rewardGasLimit(152682n)-152682n>=100000n);});

test("managed or fictional oracle tiers cannot become market-priced coupons",()=>{for(const tier of [1,2,undefined])assert.equal(couponEquivalent(W,{provider:"oracle"},{...q,tier},rate,now),null);assert.ok(couponEquivalent(W,{provider:"oracle"},{...q,tier:0},rate,now));});
