const yahoo=(id,name,symbol,category='Stocks',unit='share')=>({id,name,symbol,category,unit,provider:'yahoo',source:'Yahoo Finance',url:'https://finance.yahoo.com/quote/'+encodeURIComponent(symbol)+'/',note:category==='Commodities'?'Futures contract reference; not a local spot price.':'Latest available market quote; may be delayed.'});
const crypto=(symbol,name)=>({id:symbol.toLowerCase(),name,symbol,category:'Crypto',unit:'coin',provider:'coinbase',source:'Coinbase',url:'https://www.coinbase.com/price/'+({BTC:'bitcoin',ETH:'ethereum',SOL:'solana',DOGE:'dogecoin',BNB:'bnb'}[symbol]||name.toLowerCase().replaceAll(' ','-')),note:'Spot reference in USD.'});
const manual=(id,name,category,unit,source,url,note)=>({id,name,category,unit,provider:'manual',source,url,note});
export const ASSETS=[
  ...[['USA','United States'],['GBR','United Kingdom'],['CHE','Switzerland'],['JPN','Japan'],['BRA','Brazil'],['CAN','Canada'],['CHN','China'],['EUZ','Euro area']].map(([country,label])=>({id:'bigmac-'+country.toLowerCase(),name:'Big Mac · '+label,symbol:'BIG MAC',country,category:'Food',unit:'burger',provider:'bigmac',source:'The Economist · Big Mac Index',url:'https://github.com/TheEconomist/big-mac-data',note:'Published survey converted to USD. Not a live restaurant menu price.'})),
  manual('whopper','Burger King Whopper','Food','burger','Burger King','https://www.bk.com/','Restaurant-specific price; no verified universal quote.'),
  manual('starbucks-latte','Starbucks latte','Food','cup','Starbucks','https://www.starbucks.com/menu','Size, store and region affect the price. No verified quote.'),
  manual('pizza','Margherita pizza','Food','pizza','Custom reference',null,'Choose your own restaurant reference. No verified quote.'),
  ...[['BTC','Bitcoin'],['ETH','Ethereum'],['SOL','Solana'],['BNB','BNB'],['DOGE','Dogecoin'],['XRP','XRP'],['ADA','Cardano'],['LTC','Litecoin'],['AVAX','Avalanche'],['LINK','Chainlink'],['DOT','Polkadot'],['SHIB','Shiba Inu'],['PEPE','Pepe']].map(x=>crypto(...x)),
  ...[['aapl','Apple','AAPL'],['msft','Microsoft','MSFT'],['nvda','NVIDIA','NVDA'],['tsla','Tesla','TSLA'],['amzn','Amazon','AMZN'],['googl','Alphabet','GOOGL'],['meta','Meta','META'],['nflx','Netflix','NFLX'],['coin','Coinbase','COIN'],['mcd','McDonald’s shares','MCD'],['qsr','Restaurant Brands · Burger King','QSR'],['sbux','Starbucks shares','SBUX'],['rblx','Roblox','RBLX'],['dis','Disney','DIS'],['nke','Nike','NKE'],['pltr','Palantir','PLTR'],['gme','GameStop','GME'],['amc','AMC','AMC'],['hood','Robinhood','HOOD']].map(x=>yahoo(...x)),
  ...[['gold','Gold','GC=F','troy oz'],['silver','Silver','SI=F','troy oz'],['platinum','Platinum','PL=F','troy oz'],['palladium','Palladium','PA=F','troy oz'],['copper','Copper','HG=F','lb'],['oil-wti','WTI crude oil','CL=F','barrel'],['oil-brent','Brent crude oil','BZ=F','barrel'],['natural-gas','Natural gas','NG=F','MMBtu'],['corn','Corn','ZC=F','bushel'],['wheat','Wheat','ZW=F','bushel'],['soybeans','Soybeans','ZS=F','bushel'],['coffee','Coffee','KC=F','lb'],['sugar','Sugar','SB=F','lb'],['cocoa','Cocoa','CC=F','tonne'],['cotton','Cotton','CT=F','lb']].map(([id,name,symbol,unit])=>yahoo(id,name,symbol,'Commodities',unit)),
  ...[['sp500','S&P 500','^GSPC'],['nasdaq','Nasdaq 100','^NDX'],['dow','Dow Jones','^DJI'],['vix','Volatility index','^VIX']].map(([id,name,symbol])=>yahoo(id,name,symbol,'Indices','points')),
  {id:'coal-kg',name:'Coal · 1 kilogram',category:'Commodities',unit:'kg',provider:'oracle',feedKey:'commodity:coal',divisor:1000,source:'Launchpad on-chain index',url:'https://bscscan.com/address/0xCd880c37Df6BA0889F5Cf2398D2F25B9b7bF6011',note:'Manual index per tonne divided by 1,000. Check the update date.'},
  {id:'eggs',name:'Eggs · a dozen',category:'Food',unit:'dozen',provider:'oracle',feedKey:'commodity:eggs',source:'Launchpad on-chain index',url:'https://bscscan.com/address/0xCd880c37Df6BA0889F5Cf2398D2F25B9b7bF6011',note:'Manual index. Not a live retail quote.'},
  ...[['awp-asiimov','AWP Asiimov · Field-Tested','cs2:awp-asiimov-ft'],['karambit','Karambit Doppler · Factory New','cs2:karambit-doppler-fn'],['ak-redline','AK-47 Redline · Field-Tested','cs2:ak-redline-ft']].map(([id,name,feedKey])=>({id,name,feedKey,category:'Game items',unit:'item',provider:'oracle',source:'Launchpad on-chain feed',url:'https://bscscan.com/address/0xCd880c37Df6BA0889F5Cf2398D2F25B9b7bF6011',note:'Stored reference. Wear and variant affect market value; check freshness.'})),
  manual('charizard','Charizard · Base Set · PSA 10','Collectibles','card','PriceCharting','https://www.pricecharting.com/category/pokemon-cards','Edition and grade must match. No verified automated quote.'),
  manual('pikachu','Pikachu Illustrator card','Collectibles','card','PriceCharting','https://www.pricecharting.com/category/pokemon-cards','Auction-dependent reference. No verified automated quote.'),
  manual('rolex','Rolex Submariner','Collectibles','watch','Rolex','https://www.rolex.com/watches/submariner','Model, year and condition affect value. No verified automated quote.'),
  manual('lego','LEGO Millennium Falcon','Collectibles','set','LEGO','https://www.lego.com/','Edition and condition affect value. No verified automated quote.'),
  manual('sneakers','Air Jordan 1 · Chicago','Collectibles','pair','Custom reference',null,'Size, release and condition affect value. No verified quote.'),
  manual('cocaine-index','Cocaine · published research index','Unusual','research index','EUDA · price statistics','https://www.euda.europa.eu/data/stats2026/ppp_en','Historical public research, not a current tradable quote. No single global price is available.'),
  manual('moon-land','One acre on the Moon','Unusual','fictional acre','Fictional reference',null,'Meme concept only. No verified market price or ownership claim.'),
  manual('touch-grass','Touching grass','Unusual','moment','Fictional reference',null,'A meme reference. No market quote.'),
  manual('custom','Your own reference','Unusual','reference','Custom reference',null,'Name an item, commodity or idea. No automated quote.')
];
export const BY_ID=new Map(ASSETS.map(a=>[a.id,a]));
export const CATEGORIES=['All','Food','Stocks','Crypto','Commodities','Indices','Game items','Collectibles','Unusual'];
export function assetFromKey(key){return typeof key==='string'&&key.startsWith('anything:')?BY_ID.get(key.slice(9)):undefined}
export function referenceKey(id,custom=''){if(!BY_ID.has(id))throw Error('Unknown asset reference.');if(id==='custom'){const name=custom.trim();if(!name||name.length>80)throw Error('Enter a custom reference of 1–80 characters.');return 'Custom: '+name}return 'anything:'+id}
export function ownTokens(tokens,owner){return owner?tokens.filter(t=>t.creator.toLowerCase()===owner.toLowerCase()):[]}
