const yahoo=(id,name,symbol,category='Stocks',unit='share')=>({id,name,symbol,category,unit,provider:'yahoo',source:'Yahoo Finance',url:'https://finance.yahoo.com/quote/'+encodeURIComponent(symbol)+'/',note:category==='Commodities'?'Futures contract reference; not a local spot price.':'Latest available market quote; may be delayed.'});
const crypto=(symbol,name)=>({id:symbol.toLowerCase(),name,symbol,category:'Crypto',unit:'coin',provider:'coinbase',source:'Coinbase',url:'https://www.coinbase.com/price/'+({BTC:'bitcoin',ETH:'ethereum',SOL:'solana',DOGE:'dogecoin',BNB:'bnb'}[symbol]||name.toLowerCase().replaceAll(' ','-')),note:'Spot reference in USD.'});
export const ASSETS=[
  ...[['USA','United States'],['GBR','United Kingdom'],['CHE','Switzerland'],['JPN','Japan'],['BRA','Brazil'],['CAN','Canada'],['CHN','China'],['EUZ','Euro area']].map(([country,label])=>({id:'bigmac-'+country.toLowerCase(),name:'Big Mac · '+label,symbol:'BIG MAC',country,category:'Food',unit:'burger',provider:'bigmac',source:'The Economist · Big Mac Index',url:'https://github.com/TheEconomist/big-mac-data',note:'Published survey converted to USD. Not a live restaurant menu price.'})),
  ...[['BTC','Bitcoin'],['ETH','Ethereum'],['SOL','Solana'],['BNB','BNB'],['DOGE','Dogecoin'],['XRP','XRP'],['ADA','Cardano'],['LTC','Litecoin'],['AVAX','Avalanche'],['LINK','Chainlink'],['DOT','Polkadot'],['SHIB','Shiba Inu'],['PEPE','Pepe']].map(x=>crypto(...x)),
  ...[['aapl','Apple','AAPL'],['msft','Microsoft','MSFT'],['nvda','NVIDIA','NVDA'],['tsla','Tesla','TSLA'],['amzn','Amazon','AMZN'],['googl','Alphabet','GOOGL'],['meta','Meta','META'],['nflx','Netflix','NFLX'],['coin','Coinbase','COIN'],['mcd','McDonald’s shares','MCD'],['qsr','Restaurant Brands · Burger King','QSR'],['sbux','Starbucks shares','SBUX'],['rblx','Roblox','RBLX'],['dis','Disney','DIS'],['nke','Nike','NKE'],['pltr','Palantir','PLTR'],['gme','GameStop','GME'],['amc','AMC','AMC'],['hood','Robinhood','HOOD']].map(x=>yahoo(...x)),
  ...[['gold','Gold','GC=F','troy oz'],['silver','Silver','SI=F','troy oz'],['platinum','Platinum','PL=F','troy oz'],['palladium','Palladium','PA=F','troy oz'],['copper','Copper','HG=F','lb'],['oil-wti','WTI crude oil','CL=F','barrel'],['oil-brent','Brent crude oil','BZ=F','barrel'],['natural-gas','Natural gas','NG=F','MMBtu'],['corn','Corn','ZC=F','bushel'],['wheat','Wheat','ZW=F','bushel'],['soybeans','Soybeans','ZS=F','bushel'],['coffee','Coffee','KC=F','lb'],['sugar','Sugar','SB=F','lb'],['cocoa','Cocoa','CC=F','tonne'],['cotton','Cotton','CT=F','lb']].map(([id,name,symbol,unit])=>yahoo(id,name,symbol,'Commodities',unit)),
  ...[['sp500','S&P 500','^GSPC'],['nasdaq','Nasdaq 100','^NDX'],['dow','Dow Jones','^DJI'],['vix','Volatility index','^VIX']].map(([id,name,symbol])=>yahoo(id,name,symbol,'Indices','points')),
  ...[['awp-asiimov','AWP Asiimov · Field-Tested','cs2:awp-asiimov-ft'],['karambit','Karambit Doppler · Factory New','cs2:karambit-doppler-fn'],['ak-redline','AK-47 Redline · Field-Tested','cs2:ak-redline-ft']].map(([id,name,feedKey])=>({id,name,feedKey,category:'Game items',unit:'item',provider:'oracle',source:'Launchpad on-chain feed',url:'https://bscscan.com/address/0xCd880c37Df6BA0889F5Cf2398D2F25B9b7bF6011',note:'Stored reference. Wear and variant affect market value; check freshness.'})),
];
export const BY_ID=new Map(ASSETS.map(a=>[a.id,a]));
export const CATEGORIES=['All','Food','Stocks','Crypto','Commodities','Indices','Game items'];
export function assetFromKey(key){return typeof key==='string'&&key.startsWith('anything:')?BY_ID.get(key.slice(9)):undefined}
export function referenceKey(id){if(!BY_ID.has(id))throw Error('Choose a supported asset with a price source.');return 'anything:'+id}
export function ownTokens(tokens,owner){return owner?tokens.filter(t=>t.creator.toLowerCase()===owner.toLowerCase()):[]}
