// Stable IDs are stored in token metadata. These are fictional concepts, never price feeds.
const groups=[
  ['Tiny creatures',[
    ['fly-share','Housefly Inc. · 1 share','share','A blue-chip fly with a three-day business plan.','муха мухи акция акции'],
    ['mosquito-ipo','Mosquito IPO','share','Pre-revenue. Post-bite.'],
    ['ant-pension','Ant pension fund','fund unit','Thirty years of carrying crumbs.'],
    ['snail-lambo','A snail’s Lamborghini','ride','Zero to leaf in six business days.'],
    ['pigeon-startup','Pigeon startup equity','share','Disrupting the breadcrumb economy.'],
    ['cockroach-bunker','Cockroach bunker rent','month','The tenant will outlive the building.'],
    ['bee-bonus','A bee’s annual bonus','bonus','Paid entirely in imaginary pollen.'],
    ['moth-lamp','Moth lamp subscription','month','Premium access to the same light bulb.'],
    ['hamster-wheel','Hamster wheel energy','spin','The tiniest fictional power plant.'],
    ['spider-web','Spider web broadband','connection','Eight legs. One terrible router.'],
    ['frog-pond','Frog pond penthouse','night','Waterfront is included.'],
    ['worm-real-estate','Worm underground real estate','plot','An imaginary basement without a ceiling.'],
    ['beetle-parking','Beetle parking permit','permit','One leaf. No guest spaces.'],
    ['butterfly-effect','One butterfly effect','flap','Results may arrive on another continent.'],
    ['goldfish-memory','Goldfish cloud storage','memory','Your files have already been forgotten.'],
    ['crab-sideways','Crab sideways futures','step','A market that only moves sideways.'],
    ['squirrel-acorn','Squirrel acorn reserve','acorn','The vault location has been forgotten.'],
    ['raccoon-fund','Raccoon garbage fund','fund unit','Diversified across three imaginary bins.'],
    ['duck-bread','Duck bread allowance','crumb','Quantitative easing for a fictional pond.'],
    ['gecko-wall','Gecko wall lease','square inch','Vertical living, extremely small deposit.']
  ]],
  ['Internet',[
    ['wifi-bar','One Wi-Fi bar','bar','A connection held together by hope.','вайфай интернет'],
    ['forgotten-password','A forgotten password','guess','The hint is also forgotten.'],
    ['browser-tab','Your 999th browser tab','tab','You are definitely coming back to it.'],
    ['loading-percent','The last 1% of a download','percent','Estimated time remaining: emotionally difficult.'],
    ['captcha-bike','The last bicycle in a CAPTCHA','square','It might actually be a traffic light.'],
    ['unread-email','One unread email','email','A fictional liability from 2017.'],
    ['buffering-second','One buffering second','second','Longer when someone is watching.'],
    ['lost-cursor','A lost mouse cursor','cursor','Probably on the other imaginary monitor.'],
    ['404-page','Premium 404 page','page','Exclusive access to absolutely nothing.'],
    ['cookie-popup','One cookie popup','popup','An imaginary cookie you cannot eat.'],
    ['blue-screen','Blue screen insurance','policy','Fictional coverage. Real emotional damage.'],
    ['reply-guy','A reply-guy opinion','opinion','Unrequested. Unlimited supply.'],
    ['viral-moment','Five seconds of internet fame','moment','The algorithm has already moved on.'],
    ['ratio-futures','Ratio futures','ratio','An entirely imaginary attention market.'],
    ['ghost-follower','One ghost follower','follower','Has not logged in since forever.'],
    ['autocorrect','An autocorrect disaster','typo','Sent to the wrong imaginary group chat.'],
    ['incognito-tab','An incognito tab’s alibi','alibi','Claims it was never here.'],
    ['notification-dot','A red notification dot','dot','You will click it.'],
    ['zip-file','A zip file inside a zip file','archive','The digital version of a smaller box.'],
    ['terms-scroll','A terms-and-conditions speedrun','scroll','The world’s least-read fictional novel.']
  ]],
  ['Office life',[
    ['meeting-email','A meeting that could be an email','hour','The agenda is another meeting.'],
    ['printer-ink','Imaginary printer ink','drop','It ran out while printing this description.'],
    ['spreadsheet-cell','A suspicious spreadsheet cell','cell','Nobody knows who changed the formula.'],
    ['coffee-break','An extended coffee break','minute','Compounding at the water cooler.'],
    ['reply-all','An accidental reply-all','reply','A fictional all-hands emergency.'],
    ['calendar-gap','An empty calendar slot','minute','The rarest imaginary office commodity.'],
    ['zoom-mute','A forgotten mute button','click','You have been talking to yourself.'],
    ['office-chair','The good office chair','seat','Everyone claims it was theirs first.'],
    ['urgent-task','A non-urgent urgent task','task','Due yesterday. Started tomorrow.'],
    ['corporate-synergy','One unit of corporate synergy','synergy','Nobody can define the underlying asset.'],
    ['excel-wizard','A spreadsheet wizard’s spell','formula','Summons one perfectly aligned column.'],
    ['monday-motivation','Monday motivation reserve','drop','Usually depleted before breakfast.'],
    ['friday-energy','Friday 4:59 PM energy','second','A purely fictional productivity spike.'],
    ['out-of-office','An out-of-office reply','day','Mentally activated all year.'],
    ['desk-plant','A desk plant’s promotion','promotion','The most consistent performer.'],
    ['paperclip-fund','Paperclip hedge fund','paperclip','A small, bent portfolio.'],
    ['sticky-note','An unreadable sticky note','note','Even the author needs a translator.'],
    ['office-microwave','Office microwave diplomacy','treaty','An imaginary peace deal over lunch.'],
    ['brainstorm','An idea from the brainstorm','idea','Someone just said blockchain again.'],
    ['final-final','Final_final_v27.pdf','revision','This is definitely the final version.']
  ]],
  ['Daily chaos',[
    ['sleep-debt','Sleep debt futures','hour','An imaginary loan from tomorrow morning.','сон сна'],
    ['lost-sock','The missing left sock','sock','Last seen entering a parallel washing machine.'],
    ['alarm-snooze','One more snooze','minute','Five minutes with fictional compound interest.'],
    ['queue-place','A place in the wrong queue','position','You have been waiting for nothing.'],
    ['cold-side','The cold side of the pillow','side','A fictional luxury with rapid depreciation.'],
    ['lost-keys','Keys you just put down','key','They were here ten imaginary seconds ago.'],
    ['phone-percent','The last 1% battery','percent','A fictional race against the charger.'],
    ['charger-angle','The perfect charger angle','degree','Do not breathe near the cable.'],
    ['shopping-bag','A bag full of other bags','bag','Recursive household finance.'],
    ['laundry-chair','The laundry chair portfolio','garment','Neither clean nor officially dirty.'],
    ['elevator-smalltalk','Elevator small talk','sentence','Weather discussion priced in awkwardness.'],
    ['door-doubt','Did I lock the door?','doubt','A recurring fictional subscription.'],
    ['fridge-light','The fridge light’s secret life','minute','Nobody knows what happens when it closes.'],
    ['weekend-minute','The last minute of the weekend','minute','An imaginary asset with Monday risk.'],
    ['bus-missed','The bus you just missed','second','It waited until you started running.'],
    ['umbrella-forgotten','A forgotten umbrella','umbrella','Demand peaks exactly when you leave it home.'],
    ['shopping-cart-wheel','A rogue shopping-cart wheel','turn','Independent monetary and steering policy.'],
    ['bubble-wrap','One unpopped bubble','pop','A tiny fictional stress reserve.'],
    ['remote-gap','The remote under the sofa','remote','Traded in the deepest liquidity gap.'],
    ['one-more-episode','One more episode futures','episode','Matures at 3 AM.']
  ]],
  ['Space',[
    ['mars-parking','A parking spot on Mars','spot','Fictional property. Rover not included.'],
    ['cloud-rent','Cloud rental','hour','A lease with absolutely no fixed address.','облако облака аренда'],
    ['black-hole-storage','Black hole storage','gigabyte','Unlimited uploads. No withdrawals.'],
    ['alien-roaming','Alien roaming charges','minute','An imaginary call outside your galaxy.'],
    ['moon-shadow','A Moon shadow','shadow','Only available when the lighting agrees.'],
    ['saturn-ring','A seat on Saturn’s rings','seat','Pure fantasy. No orbital ownership.'],
    ['pluto-status','Pluto’s planet status','vote','An imaginary identity crisis index.'],
    ['comet-tail','A comet’s tail extension','metre','Cosmic glamour with fictional delivery.'],
    ['stardust-jar','A jar of imaginary stardust','jar','Sparkles cannot be redeemed.'],
    ['ufo-valet','UFO valet parking','landing','We lost your imaginary saucer.'],
    ['wormhole-toll','A wormhole toll ticket','trip','Distance-based pricing has resigned.'],
    ['gravity-break','One minute without gravity','minute','A floating fictional lunch break.'],
    ['asteroid-detour','An asteroid detour','turn','The scenic route through nowhere.'],
    ['venus-sauna','Venus sauna membership','month','An impossible fictional spa package.'],
    ['milky-way-wifi','Milky Way Wi-Fi','connection','Coverage excludes most of the universe.'],
    ['cosmic-silence','One second of cosmic silence','second','An imaginary noise-cancelling upgrade.'],
    ['moon-cheese','A slice of Moon cheese','slice','Entirely fictional dairy.'],
    ['neptune-beach','Neptune beach reservation','day','There is no real beach booking.'],
    ['galaxy-naming','An imaginary galaxy nickname','name','No scientific naming rights included.'],
    ['space-dust-tax','Intergalactic dust tax','dust unit','A fictional bill from nowhere.']
  ]],
  ['Fantasy',[
    ['dragon-rent','Dragon cave rent','month','Imaginary tenant. Very warm deposit.'],
    ['wizard-mana','Wizard mana refill','mana','A fantasy reference with no actual potion.'],
    ['npc-salary','An NPC’s salary','payday','Paid to repeat the same three sentences.','нпс зарплата'],
    ['goblin-bonus','Goblin overtime bonus','bonus','An imaginary payslip written on a rock.'],
    ['unicorn-horn','Unicorn horn polish','drop','For a completely fictional creature.'],
    ['invisibility','Invisible cloak dry cleaning','wash','The item is impossible to find.'],
    ['extra-life','An extra life receipt','life','A fictional respawn coupon.'],
    ['boss-health','The boss’s last health point','HP','One imaginary hit away from payday.'],
    ['side-quest','An abandoned side quest','quest','The imaginary village is still waiting.'],
    ['loot-luck','Loot-drop luck','luck unit','A meme concept, not a gambling product.'],
    ['portal-maintenance','Portal maintenance fee','portal','Your imaginary destination is offline.'],
    ['troll-bridge','Troll bridge season pass','pass','A fantasy toll without an actual crossing.'],
    ['ghost-rent','A ghost’s rent arrears','month','The tenant keeps disappearing.'],
    ['vampire-sunscreen','Vampire sunscreen','bottle','An imaginary product with terrible reviews.'],
    ['werewolf-barber','Werewolf haircut','trim','The appointment repeats every full moon.'],
    ['elf-retirement','Elf retirement plan','year','The vesting period is several centuries.'],
    ['fairy-overtime','Fairy dust overtime','shift','A fictional labour dispute in a tiny office.'],
    ['mimic-chest','Mimic chest security deposit','chest','The imaginary safe bites back.'],
    ['magic-bean','A suspicious magic bean','bean','No actual beanstalk performance guaranteed.'],
    ['cursed-spoon','A mildly cursed spoon','spoon','Every soup tastes like a side quest.']
  ]],
  ['Food absurdity',[
    ['last-fry','The last French fry','fry','A fictional diplomatic incident on a plate.'],
    ['pizza-crust','A pizza crust trust fund','crust','Forgotten at the edge of the portfolio.'],
    ['soup-fork','Soup eaten with a fork','attempt','Extremely inefficient imaginary liquidity.'],
    ['invisible-sandwich','An invisible sandwich','sandwich','Zero visible calories. Zero real product.'],
    ['forbidden-snack','The forbidden midnight snack','bite','A fictional raid on the fridge.'],
    ['sad-nugget','The lonely chicken nugget','nugget','Its friends were acquired at lunch.'],
    ['ketchup-drop','The last ketchup drop','drop','An imaginary squeeze-out merger.'],
    ['croissant-air','The air inside a croissant','pocket','A fictional pastry-backed narrative.'],
    ['avocado-window','An avocado’s perfect minute','minute','Unripe yesterday. Too late tomorrow.'],
    ['instant-noodle','Instant-noodle nostalgia','packet','Priced in imaginary student memories.'],
    ['cereal-dust','The dust at the cereal bottom','spoonful','The end of a fictional breakfast cycle.'],
    ['flat-soda','A bubble in flat soda','bubble','Extremely scarce imaginary carbonation.'],
    ['pineapple-pizza','Pineapple-on-pizza debate','opinion','A permanently divided fictional market.'],
    ['burnt-toast','Burnt toast premium','slice','Accidental artisanal charcoal.'],
    ['ice-cube','A dramatic ice cube','cube','Fictional value melts under pressure.'],
    ['fridge-pickle','The ancient fridge pickle','pickle','Nobody remembers opening the jar.'],
    ['banana-curve','A banana’s curvature','degree','Technical analysis for imaginary fruit.'],
    ['emergency-cookie','Emergency cookie reserve','cookie','The fictional emergency is now.'],
    ['noodle-length','An unnecessarily long noodle','metre','A fictional spaghetti duration trade.'],
    ['empty-chip-bag','Air from a chip bag','litre','More narrative than imaginary potato.']
  ]],
  ['Odd objects',[
    ['bottled-air','Premium bottled air','jar','An imaginary jar of extremely normal nothing.','воздух банка банке'],
    ['pet-rock','A pet rock’s allowance','week','A fictional pet with zero operating costs.'],
    ['left-shoe','A left shoe with ambition','shoe','Seeking a strategic right-shoe partner.'],
    ['rubber-duck','Rubber duck consulting','hour','Explains bugs by saying absolutely nothing.'],
    ['paper-crown','A paper crown’s kingdom','kingdom','Fictional sovereignty over the kitchen table.'],
    ['mystery-cable','A cable nobody can identify','cable','Kept in case the imaginary device returns.'],
    ['empty-box','An unusually good empty box','box','You cannot possibly throw it away.'],
    ['chair-squeak','A chair’s signature squeak','squeak','A fictional audio collectible.'],
    ['tangled-earbuds','Perfectly tangled earbuds','knot','An imaginary engineering achievement.'],
    ['pen-cap','The missing pen cap','cap','A tiny fictional exit liquidity event.'],
    ['dust-bunny','Dust bunny population','bunny','A fictional ecosystem under the sofa.'],
    ['door-hinge','A dramatic door hinge','creak','Announces every imaginary arrival.'],
    ['spare-button','A spare button’s destiny','button','Waiting thirty fictional years for a jacket.'],
    ['one-leg-table','A table’s wobbly leg','wobble','The napkin is the entire stabilisation plan.'],
    ['infinite-receipt','An absurdly long receipt','metre','You only bought a fictional bottle of water.'],
    ['fridge-magnet','A fridge magnet’s passport','stamp','World travel from one imaginary kitchen.'],
    ['backpack-crumb','A fossilised backpack crumb','crumb','An imaginary archaeological holding.'],
    ['shopping-list','A shopping list left at home','list','Perfect information in the wrong place.'],
    ['usb-flip','The third USB flip','attempt','A fictional violation of geometry.'],
    ['traffic-cone','A traffic cone’s authority','cone','Commands an entirely imaginary road.']
  ]],
  ['Degen life',[
    ['hopium-reserve','Strategic hopium reserve','dose','Fictional optimism. No chemical substance.'],
    ['copium-futures','Copium futures','dose','An imaginary excuse with a long maturity.'],
    ['diamond-hands','Diamond-hand grip strength','grip','A meme metaphor, not financial protection.'],
    ['paper-hands','Paper-hand origami','fold','A fictional portfolio folded into a crane.'],
    ['green-candle','One imaginary green candle','candle','Decorative optimism without a price prediction.'],
    ['red-candle','A red candle’s apology','apology','An entirely fictional market feeling.'],
    ['gas-fee-tear','A tear over gas fees','tear','An imaginary emotional transaction cost.'],
    ['missed-entry','The perfect entry you missed','entry','Only obvious in fictional hindsight.'],
    ['exit-plan','An unread exit strategy','plan','Printed and immediately misplaced.'],
    ['chart-line','One extra chart line','line','Now the imaginary chart definitely makes sense.'],
    ['wen-soon','One unit of soon','soon','A fictional timestamp without a date.'],
    ['dev-coffee','The developer’s last coffee','cup','A fictional dependency of the launch date.'],
    ['roadmap-promise','A roadmap checkbox','checkbox','An imaginary milestone in permanent progress.'],
    ['alpha-rumour','A rumour about a rumour','rumour','A fictional source citing itself.'],
    ['chad-confidence','Unreasonable confidence','unit','An imaginary balance sheet of pure conviction.'],
    ['weekend-liquidity','Weekend liquidity mirage','mirage','An imaginary pool seen from a distance.'],
    ['wallet-dust','Sentimental wallet dust','speck','A fictional souvenir from an old narrative.'],
    ['bull-costume','A bull-market costume','costume','A fictional outfit, not a market forecast.'],
    ['bear-hibernation','A bear’s alarm clock','alarm','Scheduled for an imaginary change of season.'],
    ['luck-reserve','A reserve of pure luck','luck unit','No real luck, returns or outcomes promised.','удача удачи запас']
  ]],
  ['Weather & time',[
    ['weekend-sun','Sunshine booked for Saturday','ray','A fictional booking the clouds can cancel.'],
    ['rain-meeting','Rain during an outdoor meeting','drop','An imaginary weather-related agenda change.'],
    ['headwind','A personalised headwind','gust','Follows your bicycle in both directions.'],
    ['weather-app','A weather app’s confidence','percent','An imaginary forecast for yesterday.'],
    ['fog-visibility','A premium patch of fog','patch','Nothing to see in this fictional asset.'],
    ['snowflake-resume','A snowflake’s resume','page','Claims to be completely unique.'],
    ['thunder-delay','Thunder’s dramatic pause','second','An imaginary sound effect with latency.'],
    ['rainbow-end','The end of an imaginary rainbow','end','No real gold or location provided.'],
    ['sunset-minute','The best minute of sunset','minute','An imaginary appointment you cannot reschedule.'],
    ['wind-hair','A hairstyle ruined by wind','gust','A fictional salon futures event.'],
    ['puddle-depth','A suspicious puddle’s depth','centimetre','The imaginary shoe discovers it first.'],
    ['autumn-leaf','A leaf’s retirement flight','flight','An imaginary seasonal career change.'],
    ['summer-memory','One summer that felt longer','memory','An entirely fictional nostalgia benchmark.'],
    ['monday-length','Monday’s perceived length','hour','A fictional day with extra duration.'],
    ['five-minutes','I’ll be there in five minutes','minute','An imaginary clock with flexible mechanics.'],
    ['time-zone-confusion','A time-zone misunderstanding','hour','The fictional call was yesterday.'],
    ['leap-day','A leap day’s annual salary','day','An imaginary payday with unusual timing.'],
    ['deadline-extension','One last deadline extension','day','The final final imaginary extension.'],
    ['perfect-timing','A second of perfect timing','second','A fictional asset impossible to schedule.'],
    ['tomorrow-plan','Tomorrow’s incredible plan','plan','An imaginary option that never expires.']
  ]]
];

export const MEME_THEMES=groups.map(([theme])=>theme);
export const MEME_ASSETS=groups.flatMap(([theme,rows])=>rows.map(([id,name,unit,note,aliases=''])=>({
  id:'meme-'+id,name,unit,note,aliases,theme,category:'Memes',provider:'meme',source:'Original meme concept',url:null
})));
