import {Contract,parseEther,ZeroHash,MaxUint256} from 'ethers';import assert from 'node:assert/strict';import {createFork,PAD,ROUTER} from './fork.mjs';import{minOutput}from'../lib/market.mjs';
const f=await createFork(),p=f.provider,W=parseEther;try{
 const signer=await p.getSigner(),owner=await signer.getAddress();
 const pad=new Contract(PAD,['function pairsCount() view returns(uint256)','function allPairs(uint256) view returns(address)','function createPair(string,string,string,bytes32,uint256) payable returns(address)','function quoteBuy(address,uint256) view returns(uint256)','function quoteSell(address,uint256) view returns(uint256)','function buy(address,uint256) payable returns(uint256)','function sell(address,uint256,uint256) returns(uint256)','function getPair(address) view returns(tuple(address token,bytes32 feedId,string assetKey,uint256 realBnb,uint256 tokenReserve,uint256 basePriceAtLaunch,address creator,uint64 createdAt,bool graduated))'],signer);
 const n=await pad.pairsCount();await(await pad.createPair('QA Coal','QACOAL','anything:bigmac-usa',ZeroHash,0)).wait();assert.equal(await pad.pairsCount(),n+1n);const address=await pad.allPairs(n),t=new Contract(address,['function balanceOf(address) view returns(uint256)','function allowance(address,address) view returns(uint256)','function approve(address,uint256) returns(bool)'],signer);
 assert.equal((await pad.getPair(address)).assetKey,'anything:bigmac-usa');
 const buy=await pad.quoteBuy(address,W('0.005'));await assert.rejects(pad.buy.staticCall(address,buy+1n,{value:W('0.005')}));await(await pad.buy(address,minOutput(buy,100),{value:W('0.005')})).wait();assert.equal(await t.balanceOf(owner),buy);
 await(await t.approve(PAD,buy)).wait();const sell=await pad.quoteSell(address,buy);await assert.rejects(pad.sell.staticCall(address,buy,sell+1n));await(await pad.sell(address,buy,minOutput(sell,100))).wait();assert.equal(await t.balanceOf(owner),0n);assert.equal(await t.allowance(owner,PAD),0n);
 await(await pad.buy(address,minOutput(await pad.quoteBuy(address,W('0.03')),100),{value:W('0.03')})).wait();assert.equal((await pad.getPair(address)).graduated,true);await assert.rejects(pad.buy.staticCall(address,0,{value:W('0.001')}));
 const router=new Contract(ROUTER,['function factory() view returns(address)','function WETH() view returns(address)','function getAmountsOut(uint256,address[]) view returns(uint256[])','function swapExactETHForTokens(uint256,address[],address,uint256) payable returns(uint256[])'],signer),wrapped=await router.WETH(),factory=new Contract(await router.factory(),['function getPair(address,address) view returns(address)'],p);const pair=await factory.getPair(address,wrapped),lp=new Contract(pair,['function balanceOf(address) view returns(uint256)'],p);assert.ok(await lp.balanceOf(owner)>0n);const before=await t.balanceOf(owner),route=[wrapped,address],dexQuote=await router.getAmountsOut(W('.001'),route);await(await router.swapExactETHForTokens(minOutput(dexQuote[1],100),route,owner,MaxUint256,{value:W('.001')})).wait();assert.ok(await t.balanceOf(owner)>before);
 console.log(JSON.stringify({result:'PASS',forkBlock:f.blockNumber,checks:['existing deployed launchpad','create token','curve buy','curve sell','slippage rejection','exact approval','graduation','LP to creator','DEX buy'],realMainnetTransactions:0}));
}finally{await f.close()}
